language: python
python:
  - "3.9"

before_install:
  - pip install pycodestyle

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install coveralls

script:
  - python -m pytest test/
  - coverage run --source="src/" -m pytest
  - pycodestyle src/ --ignore=E722,E501,E402

after_success: coveralls